name: authentication_app_laravel_sanctum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: 
  flutter:
    sdk: flutter
  flutter_secure_storage: 
  google_fonts: 
  http: 
  lottie: 
  platform_device_id:
    git:
      url: git@github.com:mwothman/platform_device_id.git
      path: platform_device_id
  provider: 
  shared_preferences: 

dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
