name: authentication_app_laravel_sanctum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.2.0
  lottie: ^3.0.0
  platform_device_id: ^1.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
